a = input('digito alto:')
print('o tipo primitivo desse valor é', type(a))
print('só tem espaços?', a.isspace())
print('É númerico?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('é alfanúmerico?', a.isalnum())
print('Está em maiusculo?', a.isupper())
print('Está em minusculos?', a.islower())
print('Está capitalizada', a.istitle())