n1 = int(input('Qual o primeiro número? '))
n2 = int(input('Qual o segundo número? '))
n3 = int(input('Qual o terceiro número? '))
print('O número com menor valor é: {}'.format(min(n1,n2,n3)))
print('O número com maior valor é: {}'.format(max(n1,n2,n3)))
